# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: openvantagedev
# "service" is the name of this project. This will also be added to your AWS resource names.
service: tms-api

frameworkVersion: "4"

provider:
  name: aws
  httpApi:
    cors: true
  stage: ${opt:stage, 'dev'}
  runtime: nodejs20.x
  region: eu-west-1
  deploymentBucket: tms-api-deployment
  environment:
    STAGE: ${self:provider.stage}
    NODE_ENV: ${self:provider.stage}
    SWAGGER_BUCKET_NAME: ${env:SWAGGER_BUCKET_NAME}
    JWT_SECRET: ${env:JWT_SECRET}
    DATABASE_URL: ${env:DATABASE_URL}
    DEFAULT_FROM_EMAIL: ${env:DEFAULT_FROM_EMAIL}
    AWS_S3_UPLOAD_BUCKET: ${env:AWS_S3_UPLOAD_BUCKET}
  
    
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:PutObjectAcl
            - s3:GetObject
            - s3:ListBucket
          Resource:
            - arn:aws:s3:::${self:provider.environment.SWAGGER_BUCKET_NAME}-${self:provider.stage}/*
            - arn:aws:s3:::${self:provider.environment.SWAGGER_BUCKET_NAME}-${self:provider.stage}

package:
  individually: true
  patterns:
    - 'node_modules/.pnpm/sharp@0.33.5/**'
    - 'node_modules/.pnpm/@prisma+client@6.3.1_prisma@6.3.1/node_modules/.prisma/client/schema.prisma'
    - 'node_modules/.pnpm/@prisma+client@6.3.1_prisma@6.3.1/node_modules/.prisma/client/libquery_engine-*'

layers:
  sharp:
    path: layer/nodejs
    name: sharp
    description: Sharp image processing library
    compatibleArchitectures:
      - x86_64
    compatibleRuntimes:
      - nodejs20.x
    
custom:
  stage: ${opt:stage, 'dev'}

  resources:
  Outputs:
    ApiUrl:
      Description: "The API Gateway URL"
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - Ref: ApiGatewayRestApi
            - ".execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}"

functions:
  api:
    handler: index.handler
    events:
      - httpApi: "*"
  fileservice:
    handler: upload/index.fileservice
    layers:
      - !Ref SharpLambdaLayer
    events:
      - http:
          path: /upload
          method: post
          cors: true
    package:
      patterns:
        - 'node_modules/sharp'
        - 'node_modules/@img'