# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: openvantagedev
# "service" is the name of this project. This will also be added to your AWS resource names.
service: tms-api

frameworkVersion: "4"

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs20.x
  region: eu-west-1
  deploymentBucket: tms-api-deployment
  environment:
    STAGE: ${self:provider.stage}
    NODE_ENV: ${self:provider.stage}
    SWAGGER_BUCKET_NAME: ${self:service}-swagger-docs
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:PutObjectAcl
            - s3:GetObject
            - s3:ListBucket
          Resource:
            - arn:aws:s3:::${self:provider.environment.SWAGGER_BUCKET_NAME}-${self:provider.stage}/*
            - arn:aws:s3:::${self:provider.environment.SWAGGER_BUCKET_NAME}-${self:provider.stage}
package:
  patterns:
    - 'node_modules/.pnpm/@prisma+client@6.0.1_prisma@6.0.1/node_modules/.prisma/client/schema.prisma'
    - 'node_modules/.pnpm/@prisma+client@6.0.1_prisma@6.0.1/node_modules/.prisma/client/libquery_engine-*'
custom:
  stage: ${opt:stage, 'dev'}

  resources:
  Outputs:
    ApiUrl:
      Description: "The API Gateway URL"
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - Ref: ApiGatewayRestApi
            - ".execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}"

functions:
  api:
    handler: index.handler
    events:
      - httpApi: "*"

resources:
  Resources:
    SwaggerBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.SWAGGER_BUCKET_NAME}-${self:provider.stage}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: ['*']
              AllowedMethods: [GET]
              AllowedOrigins: ['*']
              MaxAge: 3000

    SwaggerBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref SwaggerBucket
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: '*'
              Action: s3:GetObject
              Resource: arn:aws:s3:::${self:provider.environment.SWAGGER_BUCKET_NAME}-${self:provider.stage}/*

